name: user-statistician

on:
  schedule:
    - cron: '42 5 * * *'
  push:
    branches: [ master ]
    paths: [ '.github/workflows/userstats.yml' ]
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3

    - name: Generate the user stats image for GitHub profile
      uses: cicirello/user-statistician@v1
      with:
        colors: dark
        featured-repository: Chips-n-Salsa
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
